[project]
name = "jsbg"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = ["requests>=2.31.0"]

[project.scripts]
jsbg = "jsbg:main"   # NOTE: no .cli

[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"
